name: PROD-CD

on:
  push:
    tags:
      - v*

jobs:
  set-inputs:
    runs-on: [ubuntu-latest]
    outputs:
      branches: ${{ steps.set-branch.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 'Set branch for tag'
        id: set-branch
        run: |
          BRANCHES=$(git branch -r --contains ${{ github.ref }} | tr -d '\n')
          echo "BRANCHES=$BRANCHES" >> $GITHUB_OUTPUT
          echo "Branches are $BRANCHES."

  prod-cd:
    needs: set-inputs
    if: contains(needs.set-inputs.outputs.branches, 'master') # only run if tag is on master
    runs-on: [ubuntu-latest]
    steps:
      - name: TEST
        run: echo "Test"
