name: PROD-CD

on:
  push:
    tags:
      - v*

jobs:
  set-inputs:
    runs-on: [ubuntu-latest]
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 'Set branch for tag'
        id: set-branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          echo $raw
          BRANCH=${raw##*/}
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          echo "Branch is $BRANCH."

  prod-cd:
    needs: set-inputs
    if: ${{ needs.set-inputs.outputs.branch == 'master' }} # only run if branch is master
    runs-on: [ubuntu-latest]
    steps:
      - name: TEST
        run: echo "Test"
